// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFfZiTitf6_E-9k1AjmZPE7aCaoCwy0lY',
    appId: '1:495103697472:android:f34313977107f7a130f5a5',
    messagingSenderId: '495103697472',
    projectId: 'general-a5a35',
    databaseURL: 'https://general-a5a35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'general-a5a35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxk8FBd5vi3Yl3rXzdt_RLw8OXg_Z9J0A',
    appId: '1:495103697472:ios:1d0716240e2545e430f5a5',
    messagingSenderId: '495103697472',
    projectId: 'general-a5a35',
    databaseURL: 'https://general-a5a35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'general-a5a35.firebasestorage.app',
    iosBundleId: 'com.example.filmlerUygulamasi',
  );
}
