// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAL5n8CivF5w7Ibl3OgV2Vq-NGSRR8CXI',
    appId: '1:369868001825:android:3734534f37f814050c0960',
    messagingSenderId: '369868001825',
    projectId: 'kasim-adalan-320ed',
    databaseURL: 'https://kasim-adalan-320ed-default-rtdb.firebaseio.com',
    storageBucket: 'kasim-adalan-320ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqahMUVnfKl_Sfg6X8OYlb7JCq1sJTD7E',
    appId: '1:369868001825:ios:b0b557e2320256480c0960',
    messagingSenderId: '369868001825',
    projectId: 'kasim-adalan-320ed',
    databaseURL: 'https://kasim-adalan-320ed-default-rtdb.firebaseio.com',
    storageBucket: 'kasim-adalan-320ed.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );
}
